set names utf8;
REPLACE INTO script_texts (entry,content_default,content_loc8,sound,type,language,emote,comment) VALUES
(-1731028,'BY THE MIGHT OF THE LICH KING!','Во имя Короля-Лича!',16694,1,0,0,'saurfang SAY_AGGRO'),
(-1731029,'The ground runs red with your blood!','Земля обагрится вашей кровью!',16699,1,0,0,'saurfang SAY_FALLENCHAMPION'),
(-1731030,'Feast, my minions!','Веселитесь, слуги мои!',16700,1,0,0,'saurfang SAY_BLOODBEASTS'),
(-1731031,'You are nothing!','Ты никто!',16695,1,0,0,'saurfang SAY_SLAY_1'),
(-1731032,'Your soul will find no redemption here!','Ваши души не найдут здесь избавления!',16696,1,0,0,'saurfang SAY_SLAY_2'),
(-1731033,'I have become...DEATH!','Я вижу приближение смерти!',16698,1,0,0,'saurfang SAY_BERSERK'),
(-1731034,'I... Am... Released.','Я... Освободился...',16697,1,0,0,'saurfang SAY_DEATH'),
(-1731035,'Let\'s get a move on then! Move ou...','Тогда выдвигаемся! Быст...',16974,1,0,0,'bronzebeard SAY_INTRO_ALLY_0'),
(-1731036,'For every Horde soldier that you killed, for every Alliance dog that fell, the Lich King\'s armies grew. Even now the Val\'kyr work to raise your fallen... As Scourge.',16701,1,0,0,'saurfang SAY_INTRO_ALLY_1', 'Все павшие воины орды, все дохлые псы альянса - все пополнят армию Короля-Лича! Даже сейчас валькиры воскрешают ваших покойников, чтобы они стали частью Плети!'),
(-1731037,'Things are about to get much worse. Come, taste the power that the Lich King has bestowed upon me!','Сейчас все будет еще хуже. Идите сюда, я покажу вам, какой силой меня наделил Король-Лич!',16702,1,0,0,'saurfang SAY_INTRO_ALLY_2'),
(-1731038,'A lone orc, against the might of the Alliance?','Один орк против войска Альянса???',16970,1,0,0,'bronzebeard SAY_INTRO_ALLY_3'),
(-1731039,'Charge!','',16971,1,0,0,'bronzebeard SAY_INTRO_ALLY_4'),
(-1731040,'Hahahaha! Dwarves...','Ха-ха-ха. Дворфы!',16703,1,0,0,'saurfang SAY_INTRO_ALLY_5'),
(-1731041,'Kor\'kron, move out! Champions, watch your backs. The Scourge have been..','Кор''крон, выдвигайтесь! Герои, будьте начеку. Плеть только что...',17103,1,0,0,'overlord SAY_INTRO_HORDE_1'),
(-1731042,'Join me, father. Join me and we will crush this world in the name of the Scourge -- for the glory of the Lich King!','Присоеденись ко мне, отец. Перейди на мою сторону, и вместе мы разрушим этот мир во имя Плети и во славу Короля-лича!',16704,1,0,0,'saurfang SAY_INTRO_HORDE_2'),
(-1731043,'My boy died at the Wrath Gate. I am here only to collect his body.','Мой мальчик погиб у Врат Гнева. Я здесь, чтобы забрать его тело.',17097,0,0,0,'overlord SAY_INTRO_HORDE_3'),
(-1731044,'Stubborn and old. What chance do you have? I am stronger, and more powerful than you ever were.','Старый упрямец. У тебя нет шансов! Я сильнее и могущественнее, чем ты можешь представить!',16705,1,0,0,'saurfang SAY_INTRO_HORDE_4'),
(-1731045,'We named him Dranosh. It means "Heart of Draenor" in orcish. I would not let the warlocks take him. My boy would be safe, hidden away by the elders of Garadar.','Мы назвали его Дранош - на орочьем это значит "Сердце Дренора". Я бы не позволил чернокнижникам збрать его. Он был бы в безопасности в Гарадаре под защитой старейшин.',17098,0,0,0,'overlord SAY_INTRO_HORDE_5'),
(-1731046,'I made a promise to his mother before she died; that I would cross the Dark Portal alone - whether I lived or died, my son would be safe. Untainted...','Я пообещал его матери, когда она умирала, что пройду через Темный Портал один. неважно, умер бы я или выжил - мой сын остался бы цел. И чист...',17099,0,0,0,'overlord SAY_INTRO_HORDE_6'),
(-1731047,'Today, I fulfill that promise.','Сегодня я исполню это обещание.',17100,0,0,0,'overlord SAY_INTRO_HORDE_7'),
(-1731048,'High Overlord Saurfang charges!','',17104,2,0,0,'overlord SAY_INTRO_HORDE_8'),
(-1731049,'Pathetic old orc. Come then heroes. Come and face the might of the Scourge!','Жалкий старик! Ну что ж, герои. Хотите узнать, сколь могущественна Плеть?',16706,1,0,0,'saurfang SAY_INTRO_HORDE_9'),
(-1731050,'%s gasps for air','',16975,2,0,0,'bronzebeard SAY_OUTRO_ALLY_1'),
(-1731051,'That was Saurfang\'s boy - the Horde commander at the Wrath Gate. Such a tragic end...','Это был сын Саурфанга – предводитель Орды у Врат Гнева. Страшный конец...',16976,0,0,0,'bronzebeard SAY_OUTRO_ALLY_2'),
(-1731052,'What in the... There, in the distance!','Да что за... Там, вдалеке!',16977,0,0,0,'bronzebeard SAY_OUTRO_ALLY_3'),
(-1731053,'Soldiers, fall in! Looks like the Horde are comin\' in to take another shot!','Солдаты, построиться! Похоже, Орда возвращается!',16978,1,0,0,'bronzebeard SAY_OUTRO_ALLY_4'),
(-1731054,'Don\'t force my hand, orc. We can\'t let you pass.','Не нарывайся, орк. Мы тебя не пропустим.',16972,0,0,0,'bronzebeard SAY_OUTRO_ALLY_5'),
(-1731055,'Behind you lies the body of my only son. Nothing will keep me from him.','У тебя за спиной лежит тело моего сына. Ничто не помешает мне его забрать.',17094,0,0,0,'overlord SAY_OUTRO_ALLY_6'),
(-1731056,'He... I can\'t do it. Get back on your ship and we\'ll spare your life.','Я… я не пущу тебя. Возвращайся на свой корабль, и мы тебя не тронем.',16973,0,0,0,'bronzebeard SAY_OUTRO_ALLY_7'),
(-1731057,'Stand down, Muradin. Let a grieving father pass.','Отступи, Мурадин. Позволь пройти скорбящему отцу.',16690,0,0,0,'varian SAY_OUTRO_ALLY_8'),
(-1731058,'No\'ku kil zil\'nok ha tar.','',17096,0,1,0,'overlord SAY_OUTRO_ALLY_9'),
(-1731059,'I will not forget this kindess. I thank you, highness.','Я не забуду вашей доброты… благодарю, Ваше Величество.',17095,0,0,0,'overlord SAY_OUTRO_ALLY_10'),
(-1731060,'I... I was not at the Wrathgate. But the soldiers who survived told me much of what happened. Your son fought with honor. He died a hero\'s death. He deserves a hero\'s burial.','Я... Я не был у Врат Гнева. Но многое узнал от выживших солдат. Твой сын сражался достойно. Он пал смертью героя. И заслуживает погребения с почестями.',16691,0,0,0,'varian SAY_OUTRO_ALLY_11'),
(-1731061,'Lady Jaina Proudmoore cries.','Леди Джайна Праудмур плачет.',16651,2,0,0,'proudmore SAY_OUTRO_ALLY_12'),
(-1731062,'Jaina, why are you crying?','Джайна, почему ты плачешь?',16692,0,0,0,'varian SAY_OUTRO_ALLY_13'),
(-1731063,'It was nothing, your majesty. Just... I\'m proud of my king.','Не было ничего, ваше величество. Просто ... Я горжусь своим королем.',16652,0,0,0,'proudmore SAY_OUTRO_ALLY_14'),
(-1731064,'Bah! Muradin, secure the deck and prepare our soldiers for an assault on the upper citadel. I\'ll send out another regiment from Stormwind.','Мурадин защищай палубу, и приготовь солдат к штурму верхних этажей Цитадели. Я вызову из Штормграда подкрепление.',16693,0,0,0,'varian SAY_OUTRO_ALLY_15'),
(-1731065,'Right away, yer majesty!','Так точно, Ваше Величество!',16979,0,0,0,'bronzebeard SAY_OUTRO_ALLY_16'),
(-1731066,'High Overlord Saurfang coughs.','',17105,2,0,0,'overlord SAY_OUTRO_HORDE_1'),
(-1731067,'High Overlord Saurfang weeps over the corpse of his son.','Верховный правитель Саурфанг плачет над трупом своего сына.',17106,2,0,0,'overlord SAY_OUTRO_HORDE_2'),
(-1731068,'You will have a proper ceremony in Nagrand next to the pyres of your mother and ancestors.','Мы похороним тебя как подобает, в Награнде, рядом с матерью и предками...',17101,0,0,0,'overlord SAY_OUTRO_HORDE_3'),
(-1731069,'Honor, young heroes... no matter how dire the battle... Never forsake it!','Помните о чести, герои... какой бы жестокой не была битва... никогда не трекайтесь от неё.',17102,0,0,0,'overlord SAY_OUTRO_HORDE_4');